### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by AAweidai** [chainx-org/threshold_signature#1]
- [x] The public key of three people A, B, and C is created under the chain, and the public key of the two-to-two sum is used as the test data
- [x] pallet's interface, storage
  - [x] The interface that generates the address, accepts the public key of the two-to-two sum as a script, and gives the corresponding address
  - [x] Verification interface, accepts an aggregate signature and innner pubkey as input, verifies root and signature

**Comment by AAweidai** [comment]
### Test Data

**Comment by AAweidai** [comment]
### Test Data
#### A
- private key : 
  "0000000000000000000000000000000000000000000000000000000000000003"
- public key: "04f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9388f7b0f632de8140fe337e62a37f3566500a99934c2231b6cb9fd7584b8e672"

#### B
- private key : 
  "B7E151628AED2A6ABF7158809CF4F3C762E7160F38B4DA56A784D9045190CFEF"
- public key: "04dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba6592ce19b946c4ee58546f5251d441a065ea50735606985e5b228788bec4e582898"

#### C
- private key : 
  "C90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B14E5C9"
- public key: "04dd308afec5777e13121fa72b9cc1b7cc0139715309b086c960e18fd969774eb8f594bb5f72b37faae396a4259ea64ed5e6fdeb2a51c6467582b275925fab1394"

**Comment by AAweidai** [comment]
### Test Data(secp256k1)
#### A
- private key :
"0000000000000000000000000000000000000000000000000000000000000003"
- public key: "04f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9388f7b0f632de8140fe337e62a37f3566500a99934c2231b6cb9fd7584b8e672"
#### B
- private key :
"B7E151628AED2A6ABF7158809CF4F3C762E7160F38B4DA56A784D9045190CFEF"
- public key: "04dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba6592ce19b946c4ee58546f5251d441a065ea50735606985e5b228788bec4e582898"
#### C
- private key :
"C90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B14E5C9"
- public key: "04dd308afec5777e13121fa72b9cc1b7cc0139715309b086c960e18fd969774eb8f594bb5f72b37faae396a4259ea64ed5e6fdeb2a51c6467582b275925fab1394"

#### A,B,C
- aggregate public key: 
"045f3b1b4ed3e06bbc9f63f872ea77798cad288bffa76344d527837481083b6337dcee6f864f0e0f779552e0aa125ae5ef2e9613744f7692fce3c2f2c5ef9ec0dc"

#### message
- hex: 
  "243F6A8885A308D313198A2E03707344A4093822299F31D0082EFA98EC4E6C89"

#### A,B
- aggregate public key: 
"04b5d07008e94b393759e7a8fdc1ade682cf6a1c11187e5f90b16a3cf9a11a9fe5ea54cef7fbdace8f69d881d43b3250f0638eb9f9f05d5fc462377ba40175de35"
- aggregate signature:
  R: "fbc653992d90879f24957687373bc81961817d160cb3bd7a1d7eb4694a6f1993"
  s: "dbc7e47d205848a02c33e947f1e5ea5b0f284ab5c609c4659ca842b1235a1cdf"

#### B,C
- aggregate public key: 
"04828b16587113846bc89ab67058fb521dbacc32660b312688e9b270fe4eacc2a20dce48305985e1b2c635396122c4972f2429f1721b4fd020f7a228ca18cff905"
- aggregate signature:
  R: "45ff116c830b6a80428e79e5047497879509c307c985795ee43505185937bf01"
  s: "f1381b73fca6fa382763b73fd33c0a7f5d9052e221e6ec6c427d96770d86f6aa"

#### B,C
- aggregate public key: 
"04ed8758a53267babe6cd44d62dc7cafb5454995254ed86cda657d29fab413fde82c87d05dfa89cb6f7bdd39ad1c835f141bfc8e4191c43a1caa84b5a1357339e4"
- aggregate signature:
  R: "697fc3d676ad26506a647dcd61f142d383ae0c5d34c87cd0fbd17722f94ac697"
  s: "b82936b6e6683ac40b3aed8652d451040af7105a5c4e20b1918a340842b255ba"

**Comment by 0xrjman** [comment]
# TestData(sr25519)

## CoSigner

### A

```rust
//PublicKey
4463b2d58d07b4be5df5a02258f21e5048e88762f6cac3c20437adbcbcc9de58
//PrivateKey
920bb79bc3a264c0329b4dade15ae73791a238c048f69691ac8aaf3352e7320fd69912ba23c964692dfc1074f5c4e80259db7c5dfd2da8c9ef24356b442fd579
```

### B

```rust
//PublicKey
ba4f3118fb72ffaa61e6f89c4d62a2e7442db789bd1632fd0cb46ccff25f7d34
//PrivateKey
82d5066e93ae6e13640d65ddbce32967b19e2d3a88e30f39e6942248e4b6640e4adeb6f937c9920814ba7aacee1f78d9ab165c2c4fb5d474f8c213f4a411f23f
```

### C

```rust
//PublicKey
3060a9b9d8f525fc76d050769f69cb87e1f0503cbca239a7b65dd8b30f2b8324
//PrivateKey
6a46c14cdba3799416cceda3b383badcf3debb8c9abe6f7cf4d3441a1811100bbc1eb8d6ef4bd132b4180b19a8523ee634ff51fdeade631fd715d74e53e53698
```

## Message

666666

## Aggrevate

### ABC

#### Aggrevate PublicKey

`fa87fe21ee5bd74aa18a83b3c182f021f3154f93dbb41f238b8c4e540c626140`

#### Aggrevate Signature

`469992820117dfbbb2cd91dd5ca337faf629362dc4fbb38d7709ae700776a77de4895c9f1b46298eb8d5cf674bc7601c637fc53e7bbaa4fdcba50a0ca6ed5983`

### AB

#### Aggrevate PublicKey

`744ffca9bc5f2fa2373823c5510cf757fbbcda8e257eb0c7142edfda693b2f7b`

#### Aggrevate Signature

`98d683074a37ac9bf3d08d81899071109d099ad4a006bb84662db241e507806f253c515d5f02216ec88ef91f322b583c49ea4c0e88eebc3bab32663df8019f88`

### AC

#### Aggrevate PublicKey

`10e50fc91f953e773bc8e9504b405b2ff0c86eff58abec87cb9dd75f2dea2608`

#### Aggrevate Signature

`c8a7b06e4012af93e19dd7ba8a221be1cb58ff5901a70e464c399a252558663856d3ef4157aa40b40ba3b6701a9458af9e2a51c5f933657c3f6713630b6a5f85`

### BC

#### Aggrevate PublicKey

`4c0d4c765e6e817dcc8bd46faf2dca1c5bfbbad394d37990a189f5dd5fc84c61`

#### Aggrevate Signature

`122a45826a9f6f71887d3429d45a5a77cfb23629a7103ffbf9c975b1c59f401a5fd5441968dd227ef6163ead4e1c47042be7f3571544103a52b5584153080b81`

## Mast
### tweak pubkey
`3ee8244d248f1e06f72ab7d38ee7f25024d33f555eb585e167816f03c7cde719`

### pubkey ab control block 
`fa87fe21ee5bd74aa18a83b3c182f021f3154f93dbb41f238b8c4e540c626140461222205b7b12a3ab413e75d91d4c385c1f018c9fb77c342409a85f50b27634`
